"""Scenario / Control Qualitative Context Enricher.

CLI and library tool to merge qualitative scenario functional requirements
(from scenarios.json) into quantitative dossiers generated by narrative_generator.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import time
from pathlib import Path
from typing import Any

_SCENARIO_CODE_RE = re.compile(r"([A-Za-z]{3,5}\.\d{3})", re.IGNORECASE)


def extract_scenario_code(alert_definition: str) -> str | None:
    """Extract standard scenario/control code (e.g. 'CHQD.058') from an alert definition string.

    Examples:
      'CHQD.058' -> 'CHQD.058'
      'CHQD.058_PL_RB_HIGH' -> 'CHQD.058'
      'AD_CHQD.058_01' -> 'CHQD.058'
    """
    if not alert_definition:
        return None
    s = str(alert_definition).strip()

    # Check direct match on first 8 characters (e.g. 'CHQD.058')
    if len(s) >= 8 and s[:4].isalpha() and s[4] == "." and s[5:8].isdigit():
        return s[:8].upper()

    # Regex search anywhere in the identifier
    m = _SCENARIO_CODE_RE.search(s)
    if m:
        return m.group(1).upper()

    return None


def load_scenarios_json(filepath: str | Path) -> dict[str, Any]:
    """Load scenario definitions dictionary from a JSON file."""
    p = Path(filepath)
    if not p.is_file():
        raise FileNotFoundError(f"Scenario JSON file not found: {p}")
    return json.loads(p.read_text(encoding="utf-8"))


def _escape_md(val: Any) -> str:
    if val is None:
        return "—"
    return str(val).strip().replace("|", "\\|")


def format_scenario_functional_markdown(
    scenario_code: str,
    scenario_info: dict[str, Any],
    source_file: str = "scenarios.json"
) -> str:
    """Format qualitative scenario/control logic into LLM-ready markdown with XML tags."""
    lines = [
        "<functional_requirements>",
        f"## Scenario / Control Definition: {scenario_code}\n",
        "| Attribute | Details | Source |",
        "|---|---|---|",
    ]

    # Primary attributes table
    typology = scenario_info.get("Typology", "—").replace("\n", " ")
    risk_type = scenario_info.get("Risk Type", "—")
    focal = scenario_info.get("Focal Entity", "—")
    gen_crit = scenario_info.get("Alert Generation Criteria", "—")

    lines.append(f"| Typology | {_escape_md(typology)} | {source_file} |")
    lines.append(f"| Risk Type | {_escape_md(risk_type)} | {source_file} |")
    lines.append(f"| Focal Entity | {_escape_md(focal)} | {source_file} |")
    lines.append(f"| Generation Criteria | {_escape_md(gen_crit)} | {source_file} |")
    lines.append("")

    # Prose sections — verbatim preservation
    if scenario_info.get("Conditions"):
        lines.append("### Applicable Conditions")
        lines.append(scenario_info["Conditions"].strip())
        lines.append("")

    if scenario_info.get("How to detect"):
        lines.append("### Detection Logic")
        lines.append(scenario_info["How to detect"].strip())
        lines.append("")

    if scenario_info.get("FCRM will generate an alert if"):
        lines.append("### Alert Trigger Criteria")
        lines.append(scenario_info["FCRM will generate an alert if"].strip())
        lines.append("")

    if scenario_info.get("FCRM Scenario Logic"):
        lines.append("### Scenario Logic")
        lines.append(scenario_info["FCRM Scenario Logic"].strip())
        lines.append("")

    # Profiles table
    profiles = scenario_info.get("Solution Definition Profiles", [])
    if profiles:
        lines.append("### Solution Definition Profiles")
        for prof in profiles:
            p_name = prof.get("profile", "—")
            t_codes = ", ".join(prof.get("transaction_code", [])) or "—"
            dc = ", ".join(prof.get("debit_credit", [])) or "—"
            lines.append(f"- **Profile `{p_name}`**: Transaction Codes: `[{t_codes}]` | Debit/Credit: `[{dc}]`")
        lines.append("")

    lines.append("</functional_requirements>")
    return "\n".join(lines)


def enrich_single_model_block(
    model_block: str,
    scenarios_dict: dict[str, Any],
    source_filename: str = "scenarios.json"
) -> str:
    """Enrich a single <model>...</model> block with its matching functional requirements."""
    m_id = re.search(r'<model\s+id="([^"]+)"', model_block)
    if not m_id:
        return model_block

    ad = m_id.group(1)
    scenario_code = extract_scenario_code(ad)
    if not scenario_code or scenario_code not in scenarios_dict:
        return model_block

    # Don't duplicate if functional requirements already present
    if "<functional_requirements>" in model_block:
        return model_block

    scenario_info = scenarios_dict[scenario_code]
    func_md = format_scenario_functional_markdown(scenario_code, scenario_info, source_filename)

    if "</model>" in model_block:
        return model_block.replace("</model>", f"{func_md}\n\n</model>")
    return f"{model_block}\n\n{func_md}"


def enrich_dossier_text(
    content: str,
    scenarios_dict: dict[str, Any],
    source_filename: str = "scenarios.json"
) -> str:
    """Enrich a full dossier file (which may contain one or multiple <model> tags)."""
    model_pattern = re.compile(r'(<model\s+id="[^"]+".*?</model>)', re.DOTALL)
    blocks = model_pattern.split(content)
    if len(blocks) <= 1:
        # Fallback if closing tag not found or singular
        return enrich_single_model_block(content, scenarios_dict, source_filename)

    enriched_parts = []
    for part in blocks:
        if part.strip().startswith("<model") and part.strip().endswith("</model>"):
            enriched_parts.append(enrich_single_model_block(part, scenarios_dict, source_filename))
        else:
            enriched_parts.append(part)

    return "".join(enriched_parts)


def enrich_file_or_directory(
    dossier_input: str | Path,
    scenarios_path: str | Path,
    output_target: str | Path | None = None
) -> int:
    """Process a dossier markdown file or directory of per-model files."""
    scenarios_p = Path(scenarios_path)
    scenarios_dict = load_scenarios_json(scenarios_p)
    src_filename = scenarios_p.name

    in_p = Path(dossier_input)
    if not in_p.exists():
        raise FileNotFoundError(f"Input path not found: {in_p}")

    count = 0
    if in_p.is_file():
        text = in_p.read_text(encoding="utf-8")
        enriched = enrich_dossier_text(text, scenarios_dict, src_filename)
        out_p = Path(output_target) if output_target else in_p
        out_p.parent.mkdir(parents=True, exist_ok=True)
        out_p.write_text(enriched, encoding="utf-8")
        print(f"  [Enriched File] {in_p} -> {out_p}")
        count = 1
    elif in_p.is_dir():
        out_dir = Path(output_target) if output_target else in_p
        out_dir.mkdir(parents=True, exist_ok=True)
        md_files = list(in_p.glob("*.md"))
        for md_f in md_files:
            text = md_f.read_text(encoding="utf-8")
            enriched = enrich_dossier_text(text, scenarios_dict, src_filename)
            target_f = out_dir / md_f.name
            target_f.write_text(enriched, encoding="utf-8")
            count += 1
        print(f"  [Enriched Directory] {count} file(s) in {out_dir}")

    return count


def main():
    ap = argparse.ArgumentParser(
        description="Enrich quantitative TM dossiers with qualitative scenario functional logic."
    )
    ap.add_argument(
        "--scenarios-file",
        required=True,
        help="Path to scenarios JSON dictionary (e.g. scenarios.json)"
    )
    ap.add_argument(
        "--dossier-input",
        required=True,
        help="Path to dossier .md file (e.g. output/PL_RB_Q1_2026_dossiers.md) or per_model/ directory"
    )
    ap.add_argument(
        "--output-target",
        default=None,
        help="Optional output file or directory (defaults to updating in-place or specified path)"
    )
    args = ap.parse_args()

    t0 = time.perf_counter()
    print("\n[Scenario Enricher] Starting qualitative functional enrichment...")
    count = enrich_file_or_directory(
        args.dossier_input,
        args.scenarios_file,
        args.output_target
    )
    print(f"[Done] Enriched {count} dossier item(s) in {time.perf_counter() - t0:.2f}s\n")


if __name__ == "__main__":
    main()
